version: '2'
services:
  blog:
    build: .
    image: hexo-webhook
    container_name: hexo-webhook
    volumes:
      - /www/hexo:/app/hexo
    ports:
      - 8100:80
    environment:
      - CLONE_URL=      # 仓库地址
      - WEBHOOK_SECRET= # github仓库设置的secert
      # 私有仓库且通过HTTPS方式，则需要以下两项内容
      # - USER_NAME=
      # - USER_TOKEN=
    restart: unless-stopped